---
title: "Homework Bird FeederWatch Data"
format: html
editor: visual
---

```{r}

if(!require(pacman))
  install.packages("pacman")

pacman::p_load(
  C50,                # C5.0 Decision Trees and Rule-Based                            # Models
  caret,              # Classification and Regression Training
  e1071,              # Misc Functions of the Department of Statistics (e1071), TU Wien
  keras,              # R Interface to 'Keras'
  kernlab,            # Kernel-Based Machine Learning Lab
  lattice,            # Trellis Graphics for R
  MASS,               # Support Functions and Datasets for Venables and Ripley's MASS
  mlbench,            # Machine Learning Benchmark Problems
  nnet,               # Feedforward Neural Networks and Multinomial Log-Linear Models
  palmerpenguins,     # Palmer Archipelago (Antarctica) Penguin Data
  party,              # A Laboratory for Recursive Partytioning
  partykit,           # A Toolkit for Recursive Partytioning
  randomForest,       # Breiman and Cutler's Random Forests for Classification and Regression
  FSelector,          # This will bring in "RWeka & also randomForest, et al." 
  rJava,              # I think this is needed for RWeka so I'll add it here
  rpart,              # Recursive partitioning models
  RWeka,              # R/Weka Interface
  scales,             # Scale Functions for Visualization
  tidymodels,         # Tidy machine learning framework
  tidyverse,          # Tidy data wrangling and visualization
  xgboost,             # Extreme Gradient Boosting
  snow,
  dlookr, # Exploratory data analysis
  forecast, # Needed for Box-Cox transformations
  formattable, # HTML tables from R outputs
  here, # Standardizes paths to data
  kableExtra, # Alternative to formattable
  knitr, # Needed to write HTML reports
  missRanger, # To generate NAs
  tidyverse) # Powerful data wrangling package suite

### Install packages: Show fewer digits ###

options(digits=3)
```

```{r}
### Load raw data.

dataset1 <- read_csv(here('PFW_2021_public.csv'))

dataset1 |>
  #head() |>
  diagnose() |> # 361 birds (species_code)
  formattable()

dataset1

dataset1 |> summary()

dataset1 |> # Table of my N/A values: snow_dep_atleast, entry_technique, effort_hrs_atleast	
  plot_na_pareto(only_na = TRUE, plot = FALSE) |>
  formattable() # Publishable table

dataset1 |> # I like this plot.
  plot_na_pareto(only_na = TRUE)

dataset1 |> # Don't like this plot.
  plot_na_intersect(only_na = TRUE)

dataset1 <- dataset1 |>
##dataset.no_NAs_1 <- dataset1 |> 
  drop_na()



# Plot showing the results of our imputation
#rpart_na_imp_insulin |>
#  plot()

# Need these columns from the data:
# 
```

```{r}

dataset2 <- read_csv(here('PFW_count_site_data_public_2021.csv'))

dataset2 |>
  head() |>
  formattable()

dataset2

dataset2 |> summary()

dataset2 |> # Table of my N/A values.
  plot_na_pareto(only_na = TRUE, plot = FALSE) |>
  formattable() # Publishable table

dataset2 |> # I like this plot.
  plot_na_pareto(only_na = TRUE)

dataset2 |> # Don't like this plot.
  plot_na_intersect(only_na = TRUE)

### hab_water_fresh, numfeeders_etc.
```
